import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.common.serialization.ByteArraySerializer;
import org.apache.kafka.common.serialization.IntegerSerializer;

import java.util.Properties;

public class ProtobufBasicProducer {

    public static void main(String[] args) throws Exception{
        var userId = 123124;

        // TODO 1: Create a TripIntent object using class automatically generated by protoc
        /*
        RideHailingProtos.TripIntent tripIntent = RideHailingProtos.TripIntent.newBuilder()
                .setUserId(userId)
                .setLatLonFrom("48.2026,16.3688")
                .setLatLonTo("48.1869,16.3133")
                .build();

         */

        var props = new Properties();
        props.setProperty("bootstrap.servers", "localhost:9092");
        props.setProperty("key.serializer", IntegerSerializer.class.getName());

        // TODO 4: Choose the right serializer
        props.setProperty("value.serializer", ByteArraySerializer.class.getName());

        // TODO 2: Adjust the types, and convert TripIntent to bytes before sending
        KafkaProducer<Integer, byte[]> producer = new KafkaProducer(props);
        // TODO 3: Convert the object to byte array
      //  ProducerRecord<Integer, byte[]> r = new ProducerRecord<>("trip-intent", userId, tripIntent.toByteArray());
       // producer.send(r).get();
    }
}
